#ifndef TOKEN_TYPE_H_INCLUDED
#define TOKEN_TYPE_H_INCLUDED

#define TOK_IDENT	'I'
#define TOK_NUMBER	'N'
#define TOK_CONST	'C'
#define TOK_VAR		'V'
#define TOK_PROCEDURE	'P'
#define TOK_CALL	'c'
#define TOK_BEGIN	'B'
#define TOK_END		'E'
#define TOK_IF		'i'
#define TOK_THEN	'T'
#define TOK_ELSE	'e'
#define TOK_WHILE	'W'
#define TOK_DO		'D'
#define TOK_ODD		'O'
#define TOK_DOT		'.'
#define TOK_EQUAL	'='
#define TOK_COMMA	','
#define TOK_SEMICOLON	';'
#define TOK_ASSIGN	':'
#define TOK_HASH	'#'
#define TOK_LESSTHAN	'<'
#define TOK_GREATERTHAN	'>'
#define TOK_PLUS	'+'
#define TOK_MINUS	'-'
#define TOK_MULTIPLY	'*'
#define TOK_DIVIDE	'/'
#define TOK_LPAREN	'('
#define TOK_RPAREN	')'
#define TOK_WRITEINT 'w'
#define TOK_WRITECHAR 'H'
#define TOK_READINT 'R'
#define TOK_READCHAR 'h'
#define TOK_INTO 'n'
#define TOK_SIZE 's'
#define TOK_LBRACK '['
#define TOK_RBRACK ']'
#define TOK_WRITESTR 'r'
#define TOK_STRING '"'
#define TOK_FORWARD 'F'
#define TOK_EXIT 'X'


#endif // TOKEN_TYPE_H_INCLUDED
